### ISSUE TITLE
Band schedule change does not work as expected

### ISSUE THREAD

**Issue by wmiler** [js8call/js8call#25]
JS8Call 2.3.1
Win10

Settings-->Frequencies>Automatically switch bands does not work as expected.

The expectation is that the radio will change frequencies between the times set and return to previously selected freq.

Example: Radio is set on 7.078, band switch is set for 7.107 between 0059z and 0130z. It would be expected that following 0130z that the radio would switch back to 7.078, but it does not.

Note: radio does move to 7.107 at 0059z with a 30s warning box.

**Comment by wmiler** [comment]
> [@wmiler](https://github.com/wmiler) [@jsherer](https://github.com/jsherer) Wyatt & Jordan, even more troublesome I find that if I set up a frequency-change table, then close JS8Call, then re-open it, the frequency changes fail to execute. If I un-tick "Automatically switch..." then tick it to enable, it still does not execute. I find that I can only get it to execute if I delete the line from the table then add it afresh. And of course as Wyatt reported, the end-time return does not work under any condition I can find.
> 
> Wyatt, can you confirm my observation that if you set up a table, close JS8Call, then re-open it, the frequency change fails to execute, even though it is enabled?

Ok I can confirm the first part of this, disabling and reenabling worked fine however.

**Comment by Joe-K0OG** [comment]
Wyatt, I just tested again on my Linux Mint 22.1 machine, and confirm that entering a line then closing JS8Call, then opening JS8Call and toggling the "Automatically switch..." box does not cause the line to execute.  Maybe there is some difference in how Windows handles this, especially considering that the functionality is clearly broken.  My only recourse is to freshly enter a line, then click "OK" and it will execute the frequency change on time (but of course, not return as it should).

I'll await a fix then will test further.

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
I have used the scheduling function quite a bit, and to my knowledge it has never reverted to the previous frequency at the end time. You have to add an entry for each frequency _transition_ that the app should make.

**Comment by Joe-K0OG** [comment]
Rob, thanks for that clarification!  That explains why the code looks like it does, and acts like it does.  Perhaps the end time column should just be removed as it is irrelevant.

73,
-Joe-
K0OG

**Comment by wmiler** [comment]
So I've had some more time to play with this, and @rruchte work around does work. 

I would like to make this a future feature request that it work within the scheduling times or eliminate the "end" time box. This would clarify things for future users. If the end time feature is kept, maybe a third box would be to which frequency to switch back to at the end time, or just track the previous freq with a var.

**Comment by Joe-K0OG** [comment]
Agreed.  I suggest we do the simpler fix of just removing the end-time setting.  I think that makes it clear and explicit what the operator wants (a second line if he wishes to change frequency again).

However, there is still a fix that needs to be implemented so that it runs as expected (per my earlier confirmation that a time program will not run after closing/reopening JS8Call).

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
Rob, that's interesting.  I found in my testing on Linux and Windows that it was *not* initiating if I set a time slot, close JS8Call, then re-open JS8Call (so it's opening within the time slot).  I could not get it to initiate unless I deleted that line and re-entered that line with a time slot that starts in a couple of minutes, then waiting until then I see it automatically kick in.  Then, if I close JS8Call and re-open it, it will not automatically kick in.  Something is broken there, so until that's fixed, the rest doesn't matter much.

If we were to keep it the way it is, then it would be good to have an on-screen instruction indicating that to switch to a different frequency at the end time, another time line must be entered.

Another question:  What happens if one time-line overlaps another?  E.g.,
40m  21:00  22:00
20m  21:30  23:00

I'm guessing that if things were working as expected, if you open JS8Call it won't know where to go if the current time is 21:45 (in the overlap time frame).  Or, is it "understood" that the start time takes precedence, in which case 21:45 would go to 20m?

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
@Joe-K0OG Interesting, my first thought is that there must either be something wrong with whatever is supposed to be periodically calling `MainWindow::tryBandHop()`, which is pretty simple itself, or there is an issue with the `m_bandHopped` property; if `m_bandHopped` is true, the dialog never pops and the frequency is never changed.

In the case of overlaps, it looks like it could potentially pop up two `SelfDestructMessageBox` dialogs. There is just a loop over the saved windows, and if the time is within the window and `m_bandHopped` is false, it pops the dialog. `m_bandHopped` gets set to true if you click "OK" on the dialog, so if you accept it, the subsequent valid window would be ignored, and if you cancel or let it expire, the dialog for the next window would pop.

I'm away from my radio right now, so I'm not sure if I can experiment effectively, but I'll see what I can figure out.

**Comment by Joe-K0OG** [comment]
Rob @rruchte if you can, test the two following condition:
1) Set a time window that will start in a few minutes from the current time, then close JS8Call.  Change the radio frequency to a different band, then re-open JS8Call.  Does it initiate the frequency change when the start time comes around?  (My test systems do not.)
2) Set a time window which includes the current time, then close JS8Call.  Change the radio frequency to a different band, then re-open JS8Call.  Does it spontaneously initiate the frequency change?  (My test systems do not.)

My results are consistent across versions 2.3.1 (release), 2.3.2-devel, and Allen's recent code.  However, 2.2.x works as it should.

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
Joe @Joe-K0OG I've been experimenting, it's starting to look like a timezone issue. In the routine, the current time is set as UTC, but the start and end windows are treated as local time. This causes the comparisons to behave unexpectedly. If I explicitly set them to UTC in the routine, it behaves as expected. I haven't looked yet, but I suspect that when the dates are set in the configurator, the instances are set as UTC, but when they are hydrated from the saved config, they are not. Was there maybe a change in QT that would affect the default timezone of `QDateTime` instances, or some work done in the app that would affect this? I'll keep digging into the details, but it looks like this is the root cause.

**Comment by rruchte** [comment]
Joe @Joe-K0OG Can you try [this patch](https://github.com/js8call/js8call/commit/de72d8e4f1b69b583fd09a2761cd4bad8237d93b) to see if it solves the problem? It looks good to me, but without a radio, the frequency changes don't actually happen.

There may be a cleaner way to do this by making sure the timezone is properly persisted and restored in the `Configuration` class. I took a look and it seems like most of that happens automagically with `QSettings`. I'm not a QT guru, so if you know how to make sure it's marshaled/unmarshaled as UTC, that's probably the better move.

**Comment by rruchte** [comment]
I figured out how to enforce UTC when the settings are read, I can make a patch for that if you think that's a better approach.

**Comment by Joe-K0OG** [comment]
@rruchte Rob, your patch works "as expected" but as I mentioned before, there is confusion when there is time-overlap in two time lines.  What happens is that every 30 seconds it switches between the two frequencies until one of the endtimes is reaches.  Is this a feature or a bug?  ;)  Ha!

I suggest that the last overlapping line if two overlap take precedence, or perhaps implement a data checker to prevent the operator from entering overlapping times, with a pop-up explaining that overlapping times are not permitted.

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
@rruchte Rob, one other minor issue:  If I open JS8Call and am within a time slot of one of the time lines, it will pop up a window to change frequency (as expected).  The problem is this:  If I cancel, then go into settings and UN-tick (de-select) the Frequencies->Automatically Switch Bands... check box, then close settings, about 30 seconds later the radio will change frequency to that program line *without* presenting any pop-up, even though I supposedly disabled automatic switching.  The de-select action is not apparently immediate.

However, if I deselect Automatically Switch Bands, close JS8Call, then re-open it, it honors my selection (it does not switch bands).  So, the problem is just that it apparently takes a couple of time-cycles before the de-selection is implemented.

73,
-Joe-
K0OG

**Comment by wmiler** [comment]
I'll take a look at this patch as soon as I figure out how to build a Windows version. Seems to work fine on Ubuntu 24.04.

**Comment by rruchte** [comment]
OK, so in 2.3.1, there are (at least) three issues with scheduling.

1. `StationList` restores the saved station times as local time instead of UTC, causing unexpected behavior [Fixed]
2. Overlapping schedule windows result in continuous frequency change prompts [Open]
3. After deselecting "Automatically Switch Bands" in configurator, prompts are still launched for a brief time [Open]

#2 is going to take some rework, I'll look at this tonight.
#3 is hopefully something simple, the first thing `MainWindow::tryBandHop()` does it check this setting, so it shouldn't be doing this. I'll look into it.

Should #2 and #3 be set up as their own issues or do we just want to keep everything schedule related here?

**Comment by Joe-K0OG** [comment]
In my opinion, keep them all here as one issue since they are so closely related. 73,-Joe-K0OGOn Jul 16, 2025, at 16:59, Rob Ruchte ***@***.***> wrote:﻿rruchte left a comment (js8call/js8call#25)
OK, so in 2.3.1, there are (at least) three issues with scheduling.…
Should #2 and #3 be set up as their own issues or do we just want to keep everything schedule related here?

**Comment by rruchte** [comment]
@Joe-K0OG Joe, can you try [this patch](https://github.com/js8call/js8call/commit/7edfcfbf8ba1b45e7a844ffb82fb7a2d8e10ec65) to see if it solves your problem with the frequency switch dialog popping up after you save the config with the "Automatically Switch Bands" box unchecked? I don't see anything obvious that would cause that to happen (`tryBandHop` just reads that setting from the config, and the config updates that choice when you push the OK button), but the configuration persistence routine was doing a lot before that property was actually updated, it's possible that the `MainWindow::tryBandHop()` was checking the property between the time you clicked "OK" and the property actually being persisted. I would expect that to be in the millisecond range, not the 30 second range, but if you're running a debug build, who knows. All I did was move the persistence of that setting to be the first operation.

For the overlapping schedule window issue, I put together [this patch](https://github.com/js8call/js8call/commit/cc427f981b7601b8f4cf37b024d9bc3d8f1920e0). I changed the routine to only try the latest in-range window. So if you have a 15:00-17:00 window and a 16:00-18:00 window, during the 16:00-17:00 overlap, only the 16:00-18:00 window will be a valid candidate.

**Comment by rruchte** [comment]
Oh, well that's weird! That shouldn't be possible. Hmmm.

**Comment by Joe-K0OG** [comment]
> Joe, can you try [this patch](https://github.com/js8call/js8call/commit/7edfcfbf8ba1b45e7a844ffb82fb7a2d8e10ec65) to see if it solves your problem with the frequency switch

@rruchte Rob, I tried your patch, and I see the same behavior, so no fix.  You should be able to duplicate this:

1) Open JS8Call, File->Settings->Frequencies, set up a time line so that your current time is between the start and end time, *AND* the frequency will change to something different than your radio's current frequency, then enable the Automatic... check box.
2) Close settings, and within about 15 seconds you should see the pop-up prompting you that it will change frequency in 30 seconds.  Click "Cancel" on this pop-up box (so that it will not change frequency).
3) Open File->Settings->Frequencies, UN-tick the "Automatic..." box, then close settings.

You will observe that in about 15 seconds, you will *NOT* see a pop-up but the frequency *WILL* change.  This should not happen since the "Automatic..." box is UN-ticked.

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
Yeah, I just saw it and [I have a fix](https://github.com/js8call/js8call/commit/79fb77aa22aca9be5218c6d3339e8e26a3e2704b), but the problem is really weird. The callback for the SelfDestructMessageBox::accepted seems to be firing even if you click the cancel button on the dialog. I've inserted a final check for the setting _within the callback_ that prevents the frequency change from firing, but I'm still not sure why the callback is running at all in this case.

**Comment by Joe-K0OG** [comment]
@rruchte Rob, I tried both the mainwindow.cpp and Configuration.cpp fixes (building with the current js8call/js8call 2.3.2 base), and all the problems persist (even number 1, building afresh).  Perhaps I am not starting with fully-modified code?  Point me to the fully-modified files to download.  I think there are only the two modified files (mainwindow.cpp and Configuration.cpp), right?

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
@Joe-K0OG The full files are in the [schedule-fixes branch](https://github.com/rruchte/js8call/tree/schedule-fixes) in my repo. 1 & 2 should be fixed, but #3 appears to actually be a problem in the `SelfDestructMessageBox` class - it appears to always emit the the "OK" button click after the timeout, even if the cancel button was clicked.

**Comment by Joe-K0OG** [comment]
@rruchte Rob, I just noticed something while re-building that I didn't notice before your latest change (this shows up on both Windows and Linux build systems):

```
C:\JTSDK64-Tools\tmp\wsjtx\mainwindow.cpp: In lambda function:
C:\JTSDK64-Tools\tmp\wsjtx\mainwindow.cpp:602:84: warning: unused parameter 'auto_switch_bands' [-Wunused-parameter]
  602 |   connect (&m_config, &Configuration::auto_switch_bands_changed, this, [this](bool auto_switch_bands){
      |                                                                               ~~~~~^~~~~~~~~~~~~~~~~
[ 92%] Building CXX object CMakeFiles/js8call.dir/AttenuationSlider.cpp.obj
```

I thought you should see that in case it is relevant to my latest report.

I verified that the behavior I previously reported is the same on Linux as on Windows.

73,
-Joe-

**Comment by rruchte** [comment]
Thanks, I'm working on some changes, will take care of that.

**Comment by rruchte** [comment]
I don't think we should uncheck the "Automatic..." box when the dialog is cancelled, I see the cancel button as a temporary thing (skip this window), vs a permanent decision (don't do scheduling anymore at all). I suggest we approach this with two changes:

1. Allow the scheduler logic to prompt for each new window, so if I have windows for 16:00-17:00 and 17:00-18:00, and I cancel the dialog at 17:00 (because I'm in the middle of a QSO or whatever), the 18:00 dialog will still be launched. This is actually the way it's supposed to work, but I had a bug that broke that. It's fixed now.
2. In the frequency schedule table, add an item to the context menu to switch to that frequency. This will initiate a manual hop, and this will reset the state of the automated scheduler like a normal hop does.

I just pushed these changes to my repo, take a look and see what you think.

**Comment by rruchte** [comment]
I forgot to mention, I did put in your #3 suggestion, the additional text in the tooltip.

**Comment by rruchte** [comment]
@Joe-K0OG Joe, Did you try with my latest code from this afternoon? It should start running again after you toggle the checkbox. There's not really a "scheduler", the routine always runs, there is just a flag that gets set and some logic around whether or not the frequency of the entry matches the current dial frequency or the last schedule window frequency. What I did was reset the flag when you toggle the checkbox and save, which should allow the dialog to launch, even after you have cancelled the dialog previously (resetting this flag to true is basically how you "restart the scheduler"). If your current frequency is the same as the scheduled frequency, the dialog will not show, could this be what's happening?

When I test #2, I get the dialog again after I re-enable the checkbox and save. Here are my two test paths:

**Starting JS8Call during a schedule window with auto band switch enabled**
- Band hop dialog is shown
- Cancel the dialog
- Open settings, uncheck auto band switch box, save settings
- Open settings again, check auto band switch box, save settings
- Band hop dialog is shown

**Starting JS8Call during a schedule window with auto band switch disabled**
- Open settings, check auto band switch box, save settings
- Band hop dialog is shown

I can't get it to not work.

**Comment by Joe-K0OG** [comment]
P.S.  I guess what I'm saying is that it is a pain to open the settings *twice* to get the scheduler running again.  This is counter-intuitive, and it would be best to have a "Restart Scheduler" button, or *at least* an off/on toggle to get it going again.  I would prefer to see a "Restart" button (with "Paused" text in the button), something like this:

    Scheduler Status: [Stopped] (press button to restart)

...or if the scheduler is currently running...

    Scheduler Status: [Running] (press button to pause)

Or something like that...

**Comment by rruchte** [comment]
I just pushed a commit that kicks the scheduler as soon as you toggle that checkbox in the config.

**Comment by Joe-K0OG** [comment]
Rob,

I'll test that this morning - thanks for working on it!  I *REALLY* appreciate you guys who can so expertly work on the code!

As you say, toggling the checkbox is not as consistent with the rest of the UI (although, in my opinion a better solution than having to open/close settings twice).  Do you think it would be better to have a button next to the checkbox, as I proposed earlier?  Or, maybe just a simple one (wihout changeable text) that just says "Restart".  That would "kick" the scheduler the same as clicking "OK" (but not close the dialog).  I'm good either way, but prefer a "Restart" button.  Maybe, even go so far as to put it on the main screen and label it "Restart Freq Sched" for the ultimate in convenience.

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
Rob,

O.k., the toggle works great!

Now, another thought to just simplify matters.  Can you do this without too much trouble?

If "Automatic..." is ticked, when "OK" is clicked do the same functionality as is done now when I toggle "Automatic..."

If you can do that, then toggling won't even be necessary, and the UI will be completely intuitive, and will remain simple from the operator's point of view.

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
@rruchte Rob, this latest change is *almost* there.  The way the UI works is intuitive, and seems to work smoothly.  

The bug I reported on Linux is still present and actually *IS* reproducible on Windows, and I just discovered how.  If I set a program like this:
<img width="746" height="143" alt="Image" src="https://github.com/user-attachments/assets/fa0e4dc7-e064-48dc-bbac-dc9650ce5f0c" />

...and right-click on the line and switch to the frequency now, it works.  However, if I edit the lines so that the second line now precedes the first line in time, like this (in other words, the two lines switch places):
<img width="743" height="141" alt="Image" src="https://github.com/user-attachments/assets/30a5889e-1f4a-4ee5-975e-136559043592" />

I find that if I right click on the 20m line and switch to the frequency now, it switches to the 40m frequency; and if I right-click on the 40m line and switch to the frequency now, it switches to 20m.  Even though the numbers are reversed on-screen, they are apparently not reversed "behind the scenes".

One final "bug" (this one may be a matter of opinion...):  If I enter a line in the Frequency Schedule table, I can not switch to that frequency until I click "OK" then re-open the Frequency schedule settings.  Don't put much effort into this one, if it's too much trouble.  I recognize that the data entry is not "saved" yet so is not actionable.

If the right-click frequency-switch problem is fixed, I think we have a good solution, especially since the UI remains the same look as before, and now just works better.

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
@rruchte **NAILED IT**  --  Excellent Rob!  It builds and runs perfectly, and the UI is quite intuitive the way it is.  Again, nice enhancement to add the "Switch now..." right-click popup option.

_Very_ minor:  I see this on both Linux & Windows when building - not a problem, but just might need a little cleanup.

C:\JTSDK64-Tools\tmp\wsjtx\Configuration.cpp: In lambda function:
C:\JTSDK64-Tools\tmp\wsjtx\Configuration.cpp:1519:44: warning: unused parameter '[ 52%] selectedBuilding CXX object CMakeFiles/js8call.dir/main.cpp.obj' [
-Wunused-parameter]
 1519 |         this, [this](const QItemSelection &selected, const QItemSelection &) {
      |                      ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from C:\JTSDK64-Tools\tmp\wsjtx\Modulator.cpp:10:

Thanks for sticking with it Rob!

73,
-Joe-
K0OG

**Comment by Joe-K0OG** [comment]
@rruchte Rob, builds clean now.

This is a question, and I don't know if it's a problem (I have never used the scheduler before since I have a minimalist station with manual tuner, and only operate when I'm present at the radio):

If I set a time schedule to 00:01 to 01:00, and it is now 00:30 and enable the scheduler, it pops up to switch the frequency.  However, if I set the time schedule to 23:59 to 01:00 and it is now 00:30, it will NOT pop up the switch frequency window.

What am I missing here?  It seems like it should work.  Is there a problem with the time calculator routine?

73,
-Joe-
K0OG

**Comment by rruchte** [comment]
@Joe-K0OG Hmmm, sounds like it. I there is some logic that looks like it should handle that, but I haven;t looked at it closely. Lemme see...

**Comment by rruchte** [comment]
@Joe-K0OG This is actually the same problem that the saved windows had - the dates for start and end of day comparisons were not configured to be UTC, so they were in local time. I fixed that and it appears to work as expected on wrap around windows now.

**Comment by rruchte** [comment]
@Joe-K0OG Excellent! Sure, I will do that now.

**Comment by wmiler** [comment]
See Rob's PR: #34

**Comment by wmiler** [comment]
#34 has been merged into 2.3.2-devel
